### ISSUE TITLE
The method 'inheritFromWidgetOfExactType' was called on null. Receiver: null Tried calling: inheritFromWidgetOfExactType()

### ISSUE THREAD

**Issue by fly512** [Baseflow/flutter_cached_network_image#110]
0.5.0

DefaultAssetBundle.of (package:flutter/src/widgets/basic.dart:4836)
createLocalImageConfiguration (package:flutter/src/widgets/image.dart:48)
 _CachedNetworkImageState._imageLoadingFailed (package:cached_network_image/cached_network_image.dart:376)
CachedNetworkImageProvider._loadAsync (package:cached_network_image/cached_network_image.dart:474)
<asynchronous suspension>
CachedNetworkImageProvider.load (package:cached_network_image/cached_network_image.dart:462)

**Comment by georgeherby** [comment]
get the following on 0.5.1
```
flutter: ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown resolving an image codec:
flutter: The method 'inheritFromWidgetOfExactType' was called on null.
flutter: Receiver: null
flutter: Tried calling: inheritFromWidgetOfExactType(DefaultAssetBundle)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
flutter: #1      DefaultAssetBundle.of (package:flutter/src/widgets/basic.dart:4871:47)
flutter: #2      createLocalImageConfiguration (package:flutter/src/widgets/image.dart:48:32)
flutter: #3      _CachedNetworkImageState._imageLoadingFailed (package:cached_network_image/cached_network_image.dart:377:20)
flutter: #4      CachedNetworkImageProvider._loadAsync (package:cached_network_image/cached_network_image.dart:475:34)
flutter: <asynchronous suspension>
flutter: #5      CachedNetworkImageProvider.load (package:cached_network_image/cached_network_image.dart:463:16)
```

**Comment by rakeshlanjewarwork** [comment]
i am also facing this exception

**Comment by zanecidan** [comment]
Same error occurred to me while pulling an image from Firebase Storage uploaded not long ago. However restarting the app seems to work again.

**Comment by NemOry** [comment]
I'm getting the same issue.

**Comment by Abgaryan** [comment]
I am getting the same issue here

**Comment by rakeshlanjewarwork** [comment]
this widget is too good but because of this exception i switched to 

https://pub.dartlang.org/packages/flutter_advanced_networkimage

**Comment by JigneshPatel23** [comment]
Any progress on this?

**Comment by renefloor** [comment]
Is this still an issue on 1.1.1?

**Comment by hebbian** [comment]
I stopped using flutter because of this exception

**Comment by georgeherby** [comment]
I am running this plugin on the beta of flutter with version 2.0.0-rc.1 and have not had any issues. I am not facing the issue mentioned above!

**Comment by renefloor** [comment]
Unclear whether or not this is still an issue

**Comment by boucoding** [comment]
same

**Comment by ahsaniq** [comment]
[FIX] 
**Step 1:** Run 'Flutter clean'.
**Step 2:** Uninstall the application from emulator or testing device.
**Step 3:** Run 'Flutter run'.
Hope it works for you.

**Comment by kw2019ltd** [comment]
Non-fatal Exception: java.lang.Exception: NoSuchMethodError: The method 'dependOnInheritedWidgetOfExactType' was called on null.
Receiver: null
Tried calling: dependOnInheritedWidgetOfExactType()
       at Theme.of(theme.dart:128)
       at .showDialog(dialog.dart:710)
       at _VideoDownloadPageState.initDownloadsDirectoryState(video_page.dart:61)
       at _VideoDownloadPageState.initState(video_page.dart:36)
       at StatefulElement._firstBuild(framework.dart:4355)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at SingleChildRenderObjectElement.mount(framework.dart:5445)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at ComponentElement.mount(framework.dart:4201)
       at ParentDataElement.mount(framework.dart:4617)
       at Element.inflateWidget(framework.dart:3194)
       at MultiChildRenderObjectElement.mount(framework.dart:5551)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at StatefulElement._firstBuild(framework.dart:4381)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at StatefulElement._firstBuild(framework.dart:4381)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at SingleChildRenderObjectElement.mount(framework.dart:5445)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at SingleChildRenderObjectElement.mount(framework.dart:5445)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at StatefulElement._firstBuild(framework.dart:4381)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at StatefulElement._firstBuild(framework.dart:4381)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at StatefulElement._firstBuild(framework.dart:4381)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at StatefulElement._firstBuild(framework.dart:4381)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at SingleChildRenderObjectElement.mount(framework.dart:5445)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at SingleChildRenderObjectElement.mount(framework.dart:5445)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at ComponentElement.mount(framework.dart:4201)
       at ParentDataElement.mount(framework.dart:4617)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at StatefulElement._firstBuild(framework.dart:4381)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at ComponentElement.performRebuild(framework.dart:4243)
       at Element.rebuild(framework.dart:3947)
       at ComponentElement._firstBuild(framework.dart:4206)
       at ComponentElement.mount(framework.dart:4201)
       at Element.inflateWidget(framework.dart:3194)
       at Element.updateChild(framework.dart:2988)
       at SliverMultiBoxAdaptorElement.updateChild(sliver.dart:1288)
       at SliverMultiBoxAdaptorElement.createChild.<fn>(sliver.dart:1273)
       at BuildOwner.buildScope(framework.dart:2412)
       at SliverMultiBoxAdaptorElement.createChild(sliver.dart:1266)
       at RenderSliverMultiBoxAdaptor._createOrObtainChild.<fn>(sliver_multi_box_adaptor.dart:354)
       at RenderObject.invokeLayoutCallback.<fn>(object.dart:1823)
       at PipelineOwner._enableMutationsToDirtySubtrees(object.dart:875)
       at RenderObject.invokeLayoutCallback(object.dart:1823)
       at RenderSliverMultiBoxAdaptor._createOrObtainChild(sliver_multi_box_adaptor.dart:343)
       at RenderSliverMultiBoxAdaptor.insertAndLayoutChild(sliver_multi_box_adaptor.dart:489)
       at RenderSliverFixedExtentBoxAdaptor.performLayout(sliver_fixed_extent_list.dart:255)
       at RenderObject.layout(object.dart:1724)
       at RenderSliverEdgeInsetsPadding.performLayout(sliver_padding.dart:134)
       at _RenderSliverFractionalPadding.performLayout(sliver.dart:1165)
       at RenderObject.layout(object.dart:1724)
       at RenderViewportBase.layoutChildSequence(viewport.dart:410)
       at RenderViewport._attemptLayout(viewport.dart:1367)
       at RenderViewport.performLayout(viewport.dart:1285)
       at RenderObject._layoutWithoutResize(object.dart:1584)
       at PipelineOwner.flushLayout(object.dart:844)
       at RendererBinding.drawFrame(binding.dart:344)
       at WidgetsBinding.drawFrame(binding.dart:774)
       at RendererBinding._handlePersistentFrameCallback(binding.dart:283)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1102)
       at SchedulerBinding.handleDrawFrame(binding.dart:1041)
       at SchedulerBinding._handleDrawFrame(binding.dart:957)

**Comment by boucoding** [comment]
For me the error was produced by the rebuilding the state by flutter in bottom navigation bar so I used the indexed stack widget

**Comment by renefloor** [comment]
@kw2019ltd I don't see CachedNetworkImage anywhere in your log. Are you sure it is because of this package? Looks like something is wrong with the use of theme in your dialog.

@boucoding was it something together with CachedNetworkImage, or just some Flutter thing?

**Comment by boucoding** [comment]
That's a flutter related

**Comment by renefloor** [comment]
I guess it's time to close this issue, as I think the issues are not related to the cachednetworkimage anymore.

**Comment by mjmon** [comment]
I encounter this error because I used a context of a widget which is not yet attached on the widget tree.
