### ISSUE TITLE
The following assertion was thrown resolving an image codec

### ISSUE THREAD

**Issue by MahdiPishguy** [Baseflow/flutter_cached_network_image#247]
```dart
════════ Exception Caught By image resource service ════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: https://scontent-cdt1-1.cdninstagram.com/v/t51.2885-15/e35/70912136_2900468373510633_3416024049636446607_n.jpg?_nc_ht=scontent-cdt1-1.cdninstagram.com&_nc_cat=109&se=7&oh=b687a3d820af0a6a6b36679bd3c70c9c&oe=5E196C02&ig_cache_key=MjE0MTYxNDM0ODI4NjY5ODIyMw%3D%3D.2&_nc_ig_catcb=1

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:464:44)
<asynchronous suspension>
#2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:449:14)
...
Image provider: AssetImage(bundle: null, name: "https://scontent-cdt1-1.cdninstagram.com/v/t51.2885-15/e35/70912136_2900468373510633_3416024049636446607_n.jpg?_nc_ht=scontent-cdt1-1.cdninstagram.com&_nc_cat=109&se=7&oh=b687a3d820af0a6a6b36679bd3c70c9c&oe=5E196C02&ig_cache_key=MjE0MTYxNDM0ODI4NjY5ODIyMw%3D%3D.2&_nc_ig_catcb=1")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#c0e10(), name: "https://scontent-cdt1-1.cdninstagram.com/v/t51.2885-15/e35/70912136_2900468373510633_3416024049636446607_n.jpg?_nc_ht=scontent-cdt1-1.cdninstagram.com&_nc_cat=109&se=7&oh=b687a3d820af0a6a6b36679bd3c70c9c&oe=5E196C02&ig_cache_key=MjE0MTYxNDM0ODI4NjY5ODIyMw%3D%3D.2&_nc_ig_catcb=1", scale: 1.0)

```

**Comment by CristianSavin** [comment]
@MahdiPishguy You have to use Image.network(your url) instead Image.assets().

**Comment by renefloor** [comment]
This is not asset image. You should use CachedNetworkImage or NetworkImage.
