### ISSUE TITLE
Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by hyuntae0117** [Baseflow/flutter_cached_network_image#344]
### Reproduction steps
My app is native with flutter module
I added this library for image caching,
but not work

### Configuration

**Version:** 2.0.0
```
2020-03-07 15:28:52.926 5772-5865/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319)
    <asynchronous suspension>
    #1      MethodChannelPathProvider.getTemporaryPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:34)
    #2      getTemporaryDirectory (package:path_provider/path_provider.dart:27)
    #3      DefaultCacheManager.getFilePath (package:flutter_cache_manager/src/cache_manager.dart:37)
    #4      new BaseCacheManager (package:flutter_cache_manager/src/cache_manager.dart:60)
    #5      new DefaultCacheManager._ (package:flutter_cache_manager/src/cache_manager.dart:34)
    #6      new DefaultCacheManager (package:flutter_cache_manager/src/cache_manager.dart:29)
    #7      CachedNetworkImageState._cacheManager (package:cached_network_image/src/cached_image_widget.dart:340)
    #8      CachedNetworkImageState._animatedWidget (package:cached_network_image/src/cached_image_widget.dart:268)
    #9      CachedNetworkImageState.build (package:cached_network_image/src/cached_image_widget.dart:203)
    #10     StatefulElement.build (package:flutter/src/widgets/framework.dart:4334)
    #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223)
    #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
    #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
    #14     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381)
    #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
    #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
    #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
    #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
    #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
    #20     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5551)
    #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
    #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
    #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
    #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
    #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
    #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
    #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
    #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
    #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
    #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
    #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
    #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
    #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
    #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
    #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
    #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
    #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
    #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
    #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
    #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
    #41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
    #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
    #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
    #44     C
2020-03-07 15:28:52.930 1043-1854/? D/ConnectivityService: filterNetworkStateForUid() uid: 10024 networkInfo: [type: WIFI[] - WIFI, state: CONNECTED/CONNECTED, reason: (unspecified), extra: "KT_GiGA_5G_C376", failover: false, available: true, roaming: false]
2020-03-07 15:28:52.930 26605-5841/? V/FA-SVC: Upload scheduled in approximately ms: 2428893
2020-03-07 15:28:52.930 26605-5841/? V/FA-SVC: Unscheduling upload
2020-03-07 15:28:52.931 1043-1854/? D/SamsungAlarmManager: Cancel Alarm calling from uid:10024 pid :26605 / op:PendingIntent{6ad468d: PendingIntentRecord{8907bf7 com.google.android.gms broadcastIntent}}
2020-03-07 15:28:52.934 26605-5841/? V/FA-SVC: Scheduling upload, millis: 2428893
2020-03-07 15:28:52.939 26605-5841/? V/FA-SVC: Background event processing time, ms: 25
2020-03-07 15:28:52.944 5772-5865/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319)
    <asynchronous suspension>
    #1      invokeMethod (package:sqflite/src/sqflite_impl.dart:20)
    #2      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:29)
    #3      SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite/src/factory_mixin.dart:25)
    #4      wrapDatabaseException (package:sqflite/src/exception_impl.dart:8)
    #5      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:25)
    #6      SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite/src/factory_mixin.dart:25)
    #7      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite/src/factory_mixin.dart:143)
    #8      getDatabasesPath (package:sqflite/sqflite.dart:168)
    #9      CacheStore._getObjectProvider (package:flutter_cache_manager/src/cache_store.dart:39)
    #10     new CacheStore (package:flutter_cache_manager/src/cache_store.dart:35)
    #11     new BaseCacheManager (package:flutter_cache_manager/src/cache_manager.dart:64)
    #12     new DefaultCacheManager._ (package:flutter_cache_manager/src/cache_manager.dart:34)
    #13     new DefaultCacheManager (package:flutter_cache_manager/src/cache_manager.dart:29)
    #14     CachedNetworkImageState._cacheManager (package:cached_network_image/src/cached_image_widget.dart:340)
    #15     CachedNetworkImageState._animatedWidget (package:cached_network_image/src/cached_image_widget.dart:268)
    #16     CachedNetworkImageState.build (package:cached_network_image/src/cached_image_widget.dart:203)
    #17     StatefulElement.build (package:flutter/src/widgets/framework.dart:4334)
    #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223)
    #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
    #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206)
    #21     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381)
    #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201)
    #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
    #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
    #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
    #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
    #27     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5551)
    #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
    #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
    #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
    #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
    #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
    #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
    #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
    #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
    #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
    #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
    #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
    #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445)
    #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194)
    #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2988)
    #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243)
    #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3947)
    #44     ComponentElement._firstBuild (pa
```

**Comment by perepechin** [comment]
I had the same issue. Please try to add the flutter_cache_manager package, and make sure to fully rebuild and run the app again.

**Comment by hyuntae0117** [comment]
@perepechin 
does it mean [flutter_cache_manager]?(https://pub.dev/packages/flutter_cache_manager#-installing-tab-)

1. I added this package on pub spec.yaml
2. [flutter clean] on android studio => after this, can't build because FileNotFoundException: ..../.android/include_flutter.groovy
3. command flutter build aar
4. run my app
5. not work

I also made [issue](https://github.com/flutter/flutter/issues/52160) on flutter github

thank you

**Comment by danielmessi13** [comment]
I had the same problem, I solved it just by closing the application completely and building it again

**Comment by qinhehu** [comment]
try `GeneratedPluginRegistrant.registerWith(flutterEngine)`

**Comment by renefloor** [comment]
> try `GeneratedPluginRegistrant.registerWith(flutterEngine)`

I also think this is needed when using it in an add-to-app configuration.
