### ISSUE TITLE
[Gifs]  Bad state: Future already completed

### ISSUE THREAD

**Issue by bounty1342** [Baseflow/flutter_cached_network_image#655]
## 🐛 Bug Report

```
I/flutter ( 1700): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 1700): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter ( 1700): The following StateError was thrown by an image listener:
I/flutter ( 1700): Bad state: Future already completed
I/flutter ( 1700):
I/flutter ( 1700): When the exception was thrown, this was the stack:
I/flutter ( 1700): #1      _decodeImage.<anonymous closure>
package:flutter_cache_manager/…/cache_managers/image_cache_manager.dart:161
I/flutter ( 1700): #2      ImageStreamCompleter.setImage
package:flutter/…/painting/image_stream.dart:630
I/flutter ( 1700): #3      MultiFrameImageStreamCompleter._emitFrame
package:flutter/…/painting/image_stream.dart:971
I/flutter ( 1700): #4      MultiFrameImageStreamCompleter._handleAppFrame
package:flutter/…/painting/image_stream.dart:895
I/flutter ( 1700): #5      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143
I/flutter ( 1700): #6      SchedulerBinding.handleBeginFrame.<anonymous closure>
package:flutter/…/scheduler/binding.dart:1056
I/flutter ( 1700): #7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
I/flutter ( 1700): #8      SchedulerBinding.handleBeginFrame
package:flutter/…/scheduler/binding.dart:1054
I/flutter ( 1700): #9      SchedulerBinding._handleBeginFrame
package:flutter/…/scheduler/binding.dart:975
I/flutter ( 1700): #13     _invoke1 (dart:ui/hooks.dart:185:10)
I/flutter ( 1700): #14     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:248:5)
I/flutter ( 1700): #15     _beginFrame (dart:ui/hooks.dart:116:31)
I/flutter ( 1700): (elided 4 frames from dart:async)
```

### Expected behavior
Work the same as MemoryImage or NetworkImage but with cache ;)

### Reproduction steps
This happen with all the gifs from my google account.
![2016-04-04](https://user-images.githubusercontent.com/6307253/135168333-ff91ef00-0bcc-4ee1-8fab-cdf02961cbbd.gif)

```
return CachedNetworkImage(
      useOldImageOnUrlChange: true,
      memCacheHeight: displaySize.height.toInt(),
      memCacheWidth: displaySize.width.toInt(),
      maxHeightDiskCache: displaySize.height.toInt(),
      maxWidthDiskCache: displaySize.width.toInt(),
      height: displaySize.height,
      width: displaySize.width,
      fit: context.read<PictureWidgetViewModel>().boxFit,
      errorWidget: (BuildContext context, String url, dynamic error) {
        CachedNetworkImage.evictFromCache(url);
        return _Error(displaySize: displaySize, error: error);
      },
      imageUrl: ImageUtils.generateExternalUrlSized(
        context.read<PictureWidgetViewModel>().imageObject.externalUrl ??
            context.read<PictureWidgetViewModel>().imageObject.p!.externalUrl!,
        TypeImage.google,
        displaySize.height.toInt(),
        displaySize.width.toInt(),
      ),
```

### Configuration
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-x64, locale en-GB)
**Version:** 3.1.0

**Platform:** 
- [X] :iphone: iOS
- [X] :robot: Android

**Comment by renefloor** [comment]
I'll have to take some time to understand this bug

**Comment by SantiagoStepInsight** [comment]
Hello, I have the same issue with Gifts.
```
════════ Exception caught by image resource service ════════════════════════════
The following StateError was thrown by an image listener:
Bad state: Future already completed

When the exception was thrown, this was the stack
#1      _decodeImage.<anonymous closure>
package:flutter_cache_manager/…/cache_managers/image_cache_manager.dart:161
#2      ImageStreamCompleter.setImage
package:flutter/…/painting/image_stream.dart:629
#3      MultiFrameImageStreamCompleter._emitFrame
package:flutter/…/painting/image_stream.dart:970
#4      MultiFrameImageStreamCompleter._handleAppFrame
package:flutter/…/painting/image_stream.dart:894
#5      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1144
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by image resource service ════════════════════════════
Bad state: Future already completed
════════════════════════════════════════════════════════════════════════════════
```
Configuration
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale en-AU)

Platform:

 📱 iOS

**Comment by renefloor** [comment]
Do you have an example url I can try to reproduce this bug?

**Comment by renefloor** [comment]
@bounty1342 sorry for the delay. I first tried to just show a gif, but that works fine. Going from your code to a bit simpler I found that the problem is with the resizing. This is the smallest example that keeps giving errors:
```dart
const _imageUrl = 'https://user-images.githubusercontent.com/6307253/135168333-ff91ef00-0bcc-4ee1-8fab-cdf02961cbbd.gif';
class GifWidget extends StatelessWidget {
  const GifWidget({Key? key}) : super(key: key);

  final int height = 300;
  final int width = 500;

  @override
  Widget build(BuildContext context) {
    return CachedNetworkImage(
        maxHeightDiskCache: height,
        imageUrl: _imageUrl
    );
  }
}
```

At first the problem is that resizing of GIFs is actually not supported. We would have to resize every frame of the gif. It's possible, but not done at the moment. Why the errors are there I still have to dig into.

It looks like you are already getting a well sized image from the backend (at least that's what `generateExternalUrlSized` makes me think), so I would at least recommend to remove these lines from your code as the gif already has the right size:
```
      memCacheHeight: displaySize.height.toInt(),
      memCacheWidth: displaySize.width.toInt(),
      maxHeightDiskCache: displaySize.height.toInt(),
      maxWidthDiskCache: displaySize.width.toInt(),
```

**Comment by renefloor** [comment]
@bounty1342 I just released an update of the cache manager: `flutter_cache_manager: ^3.1.3`. This is compatible with the latest cached_network_image. For now this disables the support for gif resizing.

**Comment by boeledi** [comment]
This bug is not only related to GIFs.  I also have it, from time to time, with PNG and JPEG.
Unfortunately, it is not systematic.
