### ISSUE TITLE
Can't load the picture on the HUAWEI devices.

### ISSUE THREAD

**Issue by Onperson** [Baseflow/flutter_cached_network_image#683]
## 🐛 Bug Report
  Recently, My company has developed the flutter home page with flutter, But we tested that Cached_network_image can't show 
up the http images on the HUAWEI os, Does it is ?

2021-11-26 10:26:41.595 32382-4012/? E/FlutterJNI: Failed to decode image
    android.graphics.ImageDecoder$DecodeException: Failed to create image decoder with message 'unimplemented'Input contained an error.
        at android.graphics.ImageDecoder.nCreate(Native Method)
        at android.graphics.ImageDecoder.access$200(ImageDecoder.java:173)
        at android.graphics.ImageDecoder$ByteBufferSource.createImageDecoder(ImageDecoder.java:250)
        at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1847)
        at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1840)
        at io.flutter.embedding.engine.FlutterJNI.decodeImage(FlutterJNI.java:431)
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by meg4cyberc4t** [comment]
I have same problem with Samsung

**Comment by renefloor** [comment]
What kind of image is this?
