### ISSUE TITLE
`StateError: Bad state: Cannot clone a disposed image` after app changes lifecycle

### ISSUE THREAD

**Issue by raulmabe** [Baseflow/flutter_cached_network_image#746]
## 🔙 Regression

Hi, I have received 300 events in 14 days in Sentry that some users are getting an error related with images and I think this package may have to do with it (as I do not manipulate images directly, nor another package that I have... Also the issue may be related to #513.). 

I am getting these two errors after app lifecycles changes.

```
StateError: Bad state: Cannot clone a disposed image.
The clone() method of a previously-disposed Image was called. Once an Image object has been disposed, it can no longer be used to create handles, as the underlying data may have been released.
  File "painting.dart", line 1815, in Image.clone
  File "image_stream.dart", line 50, in ImageInfo.clone
  File "image_stream.dart", line 645, in ImageStreamCompleter.setImage
  File "zone.dart", line 1434, in _rootRunUnary
```

```
String: Bad state: Cannot clone a disposed image.
The clone() method of a previously-disposed Image was called. Once an Image object has been disposed, it can no longer be used to create handles, as the underlying data may have been released.
  File "painting.dart", line 1815, in Image.clone
  File "image_stream.dart", line 50, in ImageInfo.clone
  File "image_stream.dart", line 645, in ImageStreamCompleter.setImage
  File "zone.dart", line 1434, in _rootRunUnary
```

### Reproduction steps

I have the following breadcrumbs (may be incomplete, but will provide more info as I get):

1. Move the app to the background
2. Resume the app

### Configuration

<details>
<summary>
flutter doctor -v
</summary>

```bash

flutter doctor -v
[✓] Flutter (Channel stable, 3.0.0, on macOS 11.6 20G165 darwin-x64, locale es-ES)
    • Flutter version 3.0.0 at /Users/raulmateobeneyto/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (2 weeks ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/raulmateobeneyto/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • ONEPLUS A6013 (mobile) • fe0fb3b5                             • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • D32273CD-17B7-4F4D-AA28-AF043DEB3851 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Plugin version: ` cached_network_image: ^3.2.1`

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android

**Comment by rahuldubey093** [comment]
Having the same issue, since last 6 months

**Comment by hbock-42** [comment]
Same here, except I don't even need to pop a page.

The exception come from:
sky_engine->ui->painting.dart
From the method: 
`Image clone() {
    if (_disposed) {
      throw StateError(
        'Cannot clone a disposed image.\n'
        'The clone() method of a previously-disposed Image was called. Once an '
        'Image object has been disposed, it can no longer be used to create '
        'handles, as the underlying data may have been released.'
      );
    }
    assert(!_image._disposed);
    return Image._(_image);
  }`

**Comment by raulmabe** [comment]
It happens only in iOS to me, I'll update the issue.

**Comment by himeshp** [comment]
Any update on this?
I can see it on both android and iOS.

**Comment by Mayb3Nots** [comment]
Hi I have this issue but I don't have `cached_network_image` as a dependency direct nor transitive so _it might be possible_ its not from this package.

**Comment by alanlanglois** [comment]
Same here, I'm using bugsnag and it happens on both iOS and android.

**Comment by Mayb3Nots** [comment]
Im pretty sure this is already fixed in the latest stable version of Flutter. Could you reproduce it with flutter 3.7.4?

**Comment by alanlanglois** [comment]
I got it in production using Flutter 3.7.7

**Comment by bartekpacia** [comment]
My app uses the (currently) latest Flutter 3.10.6, and I'm also experiencing this error after I go to home and then go back to the app. iPhone 12 mini, iOS 16.

**Comment by nicklbaert** [comment]
> My app uses the (currently) latest Flutter 3.10.6, and I'm also experiencing this error after I go to home and then go back to the app. iPhone 12 mini, iOS 16.

Did you by any chance find a solution?

**Comment by bartekpacia** [comment]
Nope, there's no solution. This package has a bug that has to be fixed.

**Comment by senenpalanca97** [comment]
Same problem here. Have been using this library for a long time without problems but now I've received in sentry a lot of events for this bug.

**Comment by kienvtqhi** [comment]
> Same problem here. Have been using this library for a long time without problems but now I've received in sentry a lot of events for this bug. EDIT: I'm using cached_network_image & blurhash.

Use `BlurHashImage` instead of. It worked for me

Before:
`BlurHash(hash: userProfile.mainPhotoBlurhash)`

After:
`Image( image: BlurHashImage(userProfile.mainPhotoBlurhash), fit: BoxFit.cover, )`

**Comment by JavierPerezLavadie** [comment]
Hello I have the same problem with flutter 3.16.8, it happened since the last update of the package with octo set and the extensions

**Comment by bartekpacia** [comment]
@kienvtqhi Sorry, this didn't work for me.

**Comment by MrrJamrotha** [comment]
my pubspece.yaml = cached_network_image: ^3.4.1

════════ Exception caught by image resource service ════════════════════════════
The following StateError was thrown by an image listener:
Bad state: Cannot clone a disposed image.
The clone() method of a previously-disposed Image was called. Once an Image object has been disposed, it can no longer be used to create handles, as the underlying data may have been released.

When the exception was thrown, this was the stack:
#0      Image.clone (dart:ui/painting.dart:2137:7)
painting.dart:2137
#1      ImageInfo.clone (package:flutter/src/painting/image_stream.dart:72:35)
image_stream.dart:72
#2      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:767:32)
image_stream.dart:767
(elided 5 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by image resource service ════════════════════════════
Bad state: Cannot clone a disposed image.
The clone() method of a previously-disposed Image was called. Once an Image object has been disposed, it can no longer be used to create handles, as the underlying data may have been released.
════════════════════════════════════════════════════════════════════════════════

**Comment by esentis** [comment]
None of the recommended fixes actually fix the issue.
