### ISSUE TITLE
SocketException: Bad file descriptor - on iOS devices

### ISSUE THREAD

**Issue by jake-bots** [Baseflow/flutter_cached_network_image#751]
Hi, we are this getting error logged on iOS devices:

```
SocketException: Bad file descriptor (OS Error: Bad file descriptor, errno = 9), address = res.cloudinary.com, port = 0: SocketException: Bad file descriptor (OS Error: Bad file descriptor, errno = 9), address = res.cloudinary.com, port = 0
#0   _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682)

#1   _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1817)

#2   RawSocket.startConnect (dart:io-patch/socket_patch.dart:27)

#3   Socket._startConnect (dart:io-patch/socket_patch.dart:2038)

#4   Socket.startConnect (dart:io/socket.dart:792)

#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2440)

#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2834)

#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2839)

#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2698)

#9      _HttpClient.getUrl (dart:_http/http_impl.dart:2575)

#10   NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:87)

#11   NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:50)

#12   ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:505)

#13   ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:380)

#14   ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:503)

#15   ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:333)

#16   ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:464)

#17   SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41)

#18   ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:461)

#19   _rootRun (dart:async/zone.dart:1426)

#20   _CustomZone.run (dart:async/zone.dart:1328)

#21   _CustomZone.runGuarded (dart:async/zone.dart:1236)

#22   ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:453)

#23   ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:330)

#24   DecorationImagePainter.paint (package:flutter/src/painting/decoration_image.dart:316)

#25   _BoxDecorationPainter._paintBackgroundImage (package:flutter/src/painting/box_decoration.dart:465)

#26   _BoxDecorationPainter.paint (package:flutter/src/painting/box_decoration.dart:483)

#27   RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2150)

#28   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#29   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#30   _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#31   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#32   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#33   RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79)

#34   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#35   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#36   _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#37   RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2169)

#38   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#39   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#40   RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847)

#41   RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078)

#42   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#43   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#44   _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7537)

#45   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#46   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#47   RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79)

#48   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#49   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#50   _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#51   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#52   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#53   _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#54   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#55   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#56   _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#57   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#58   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#59   _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#60   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#61   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#62   _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#63   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#64   PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141)

#65   PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100)

#66   PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:198)

#67   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:185)

#68   _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#69   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#70   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#71   RenderSliverMultiBoxAdaptor.paint (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:647)

#72   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#73   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#74   RenderSliverEdgeInsetsPadding.paint (package:flutter/src/rendering/sliver_padding.dart:274)

#75   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#76   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#77   RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:660)

#78   RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:645)

#79   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#80   PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141)

#81   PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100)

#82   PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:198)

#83   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:185)

#84   _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#85   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#86   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#87   _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#88   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#89   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#90   _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#91   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#92   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#93   _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#94   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#95   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#96   _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#97   RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#98   PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#99   _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#100  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#101  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#102  RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847)

#103  RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078)

#104  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#105  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#106  RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847)

#107  RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078)

#108  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#109  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#110  _RenderSingleChildViewport.paint.paintContents (package:flutter/src/widgets/single_child_scroll_view.dart:542)

#111  PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387)

#112  PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:443)

#113  _RenderSingleChildViewport.paint (package:flutter/src/widgets/single_child_scroll_view.dart:546)

#114  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#115  PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141)

#116  PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100)

#117  PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:198)

#118  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:185)

#119  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#120  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#121  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#122  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#123  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#124  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#125  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#126  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#127  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#128  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#129  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#130  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#131  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#132  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#133  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#134  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#135  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#136  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#137  RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847)

#138  RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078)

#139  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#140  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#141  RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847)

#142  RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078)

#143  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#144  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#145  RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847)

#146  RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629)

#147  RenderStack.paint (package:flutter/src/rendering/stack.dart:645)

#148  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#149  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#150  RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79)

#151  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#152  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#153  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#154  PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387)

#155  RenderAnnotatedRegion.paint (package:flutter/src/rendering/proxy_box.dart:5424)

#156  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#157  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#158  RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847)

#159  RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:408)

#160  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#161  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#162  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#163  _RenderInkFeatures.paint (package:flutter/src/material/material.dart:555)

#164  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#165  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#166  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#167  PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387)

#168  RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1929)

#169  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#170  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#171  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#172  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#173  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#174  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#175  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#176  PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141)

#177  PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100)

#178  PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:198)

#179  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:185)

#180  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#181  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#182  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#183  RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847)

#184  RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629)

#185  RenderStack.paint (package:flutter/src/rendering/stack.dart:645)

#186  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#187  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#188  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#189  RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2169)

#190  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#191  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#192  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#193  RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2784)

#194  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#195  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#196  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#197  RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2784)

#198  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#199  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#200  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#201  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#202  PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141)

#203  PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100)

#204  PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:198)

#205  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:185)

#206  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#207  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#208  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#209  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#210  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#211  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#212  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#213  RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:3443)

#214  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#215  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#216  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#217  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#218  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#219  _RenderTheatre.paintStack (package:flutter/src/widgets/overlay.dart:788)

#220  _RenderTheatre.paint (package:flutter/src/widgets/overlay.dart:806)

#221  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#222  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#223  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#224  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#225  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#226  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#227  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#228  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#229  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#230  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#231  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#232  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#233  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#234  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#235  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#236  RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:3443)

#237  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#238  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#239  RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847)

#240  RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629)

#241  RenderStack.paint (package:flutter/src/rendering/stack.dart:645)

#242  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#243  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#244  RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:79)

#245  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#246  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#247  RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847)

#248  RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629)

#249  RenderStack.paint (package:flutter/src/rendering/stack.dart:645)

#250  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#251  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#252  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#253  RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2169)

#254  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#255  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#256  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#257  PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387)

#258  PaintingContext.pushClipRRect (package:flutter/src/rendering/object.dart:479)

#259  RenderClipRRect.paint (package:flutter/src/rendering/proxy_box.dart:1545)

#260  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#261  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#262  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#263  RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2397)

#264  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#265  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#266  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#267  RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2397)

#268  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#269  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#270  RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2847)

#271  RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629)

#272  RenderStack.paint (package:flutter/src/rendering/stack.dart:645)

#273  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#274  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#275  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#276  PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:387)

#277  RenderAnnotatedRegion.paint (package:flutter/src/rendering/proxy_box.dart:5424)

#278  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#279  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#280  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#281  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#282  PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187)

#283  _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:343)

#284  RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2449)

#285  PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141)

#286  PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100)

#287  PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:995)

#288  RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:499)

#289  WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883)

#290  RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363)

#291  SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144)

#292  SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081)

#293  SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995)

#294  _rootRun (dart:async/zone.dart:1426)

#295  _CustomZone.run (dart:async/zone.dart:1328)

#296  _CustomZone.runGuarded (dart:async/zone.dart:1236)

#297  _invoke (da
```

We are using version: `cached_network_image: ^3.2.0`

Flutter doctor -v:

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-arm, locale
    en-GB)
    • Flutter version 2.10.5 at /Users/jakebots/Documents/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (8 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/jakebots/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/jakebots/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.64.2)
    • VS Code at /Users/jakebots/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

Do you have any idea why this issue would be occuring?
Thanks

**Comment by ABDERRAHMANE-OUALI** [comment]
same issue here, running on iOS emulator

**Comment by addhayam** [comment]
same here. Both on simulator and device. Both on android and ios.
