### ISSUE TITLE
Exception: Invalid image data

### ISSUE THREAD

**Issue by bxxasn** [Baseflow/flutter_cached_network_image#797]
Flutter is used on the main page_ cached_ network_ image。
The url of this image is invalid
Jumping to the next page will report this error
===============================
code:
Container(
              margin: const EdgeInsets.only(left: 20, top: 54),
              child: ClipOval(
                  child: CachedNetworkImage(
                imageUrl: avatorUrl??'',
                height: 64,
                width: 64,
                fit: BoxFit.fill,
                progressIndicatorBuilder: (context, url, downloadProgress) =>
                    CircularProgressIndicator(value: downloadProgress.progress),
                errorWidget: (context, url, error) => Image.asset(
                  'assets/images/profile/head-portrait.png',
                  width: 36,
                  height: 36,
                  fit: BoxFit.fill,
                ),
              )),
            )
===============================

======== Exception caught by image resource service ================================================
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack: 
#0      _futurize (dart:ui/painting.dart:5886:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:5741:12)
#2      instantiateImageCodecFromBuffer (dart:ui/painting.dart:2092:60)
#3      PaintingBinding.instantiateImageCodecFromBuffer (package:flutter/src/painting/binding.dart:153:15)
#4      ImageLoader.loadBufferAsync.<anonymous closure> (package:cached_network_image/src/image_provider/_image_loader.dart:68:22)
<asynchronous suspension>
#5      ImageLoader._load (package:cached_network_image/src/image_provider/_image_loader.dart:121:25)
<asynchronous suspension>
#6      new MultiImageStreamCompleter.<anonymous closure> (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:25:18)
<asynchronous suspension>
Image provider: CachedNetworkImageProvider("http://94.74.17.115/wallet-app/img/public/20221025/05hjd8b00eb47a2ad1580ec9df89456/11/635791ac6292b5aef572a183.png", scale: 1.0) 
 Image key: CachedNetworkImageProvider("http://94.74.17.115/wallet-app/img/public/20221025/05hjd8b00eb47a2ad1580ec9df89456/11/635791ac6292b5aef572a183.png", scale: 1.0): CachedNetworkImageProvider("http://94.74.17.115/wallet-app/img/public/20221025/05hjd8b00eb47a2ad1580ec9df89456/11/635791ac6292b5aef572a183.png", scale: 1.0)

**Comment by marcellocamara** [comment]
Same error here

This error appears when there is a lot of images on the same screen
This package is not able to download every one in the same time (how can we treat it?)

![Captura de Tela 2022-11-22 às 23 29 57](https://user-images.githubusercontent.com/18273071/203458771-34c9066b-a5c0-47c4-aea9-ef027106aef1.png)
![Captura de Tela 2022-11-22 às 23 30 05](https://user-images.githubusercontent.com/18273071/203458789-b0166014-fde6-4a78-879f-bffdd3a6da2b.png)

**Comment by ngonhat94** [comment]
same issue.

**Comment by ming-chu** [comment]
Looks related to #778

**Comment by HeyRonak** [comment]
Have you found any solution ? @marcellocamara @ngonhat94

**Comment by ngonhat94** [comment]
You can try package: https://pub.dev/packages/extended_image

**Comment by zhuwei** [comment]
same issue.

**Comment by rnewquist** [comment]
I have the same issue.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.83.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

I have tried Image.network, CachedNetworkImageProvider, and ExtendedNetworkImageProvider with the same error 
flutter: Exception: Invalid image data.

Here is the image link that I'm trying to load:
https://rizzcomic.com/assets/images/46_paladin-23-06-2023_11_43_54_PM.webp

**Comment by Rishyash** [comment]
For those who are getting these crash as fatal crash.
https://medium.com/@rishyash8/flutter-firebase-crash-report-because-of-connection-closed-before-full-header-was-received-7ace6e84bc5d

**Comment by mixmaker** [comment]
Sill not solved :(

both of these throws the same error
` CachedNetworkImage(
                                                imageUrl: thumbUrl,
                                                                              width: 30,
                                                                              height: 30,
                                                                            ),`

`CircleAvatar(
         radius: 30,
         backgroundImage: CachedNetworkImageProvider(thumbUrl))`

However if i use `NetworkImage(thumbUrl)`  it works just perfect.

Here's some sample images i'm using:
 [image1](https://titankoders.com/category_img/asus.jpg)  [image2](https://titankoders.com/category_img/alcatel.jpg)

**Comment by Sahilkumr** [comment]
> I have the same issue.
> 
> Doctor summary (to see all details, run flutter doctor -v): [✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-US) [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2) [✓] Xcode - develop for iOS and macOS (Xcode 15.0.1) [✓] Chrome - develop for the web [✓] Android Studio (version 2022.2) [✓] VS Code (version 1.83.0) [✓] Connected device (3 available) [✓] Network resources
> 
> • No issues found!
> 
> I have tried Image.network, CachedNetworkImageProvider, and ExtendedNetworkImageProvider with the same error flutter: Exception: Invalid image data.
> 
> Here is the image link that I'm trying to load: ![Image](https://camo.githubusercontent.com/65e34776edbaacdf3595afbc9b5cf0a558c67016e22c0b74bbd29e73f5ae3659/68747470733a2f2f72697a7a636f6d69632e636f6d2f6173736574732f696d616765732f34365f70616c6164696e2d32332d30362d323032335f31315f34335f35345f504d2e77656270)

Hey, Brother I Tried the Image with [ CachedNetworkImage, Image.Network ] it is Working Fine.
For Everyone Having Same Problem: 
Check Following things First.
1. Network[internet] is working.
2. Network Request is Okay [URL is Working].
3. Response you are getting is correct and well formatted as per your requirement [ check browser's Inspect]

**Comment by Hemant88080** [comment]
don't use "CachedNetworkImageProvider"  try to use "CachedNetworkImage"

**Comment by wantroba** [comment]
Same problem here

**Comment by sgowda97** [comment]
Facing the same issue. Any fix?

**Comment by bastibense** [comment]
Me too! Happens to me during integration testing.

I have a feeling that an exception is thrown if a CachedNetworkImage was created in Test 1, and before the test image could be loaded, Test 2 begins (and the tree/context of Test 1 is freed).

Eventually the network request will finish and in that moment there is no more Widget to update.

So from what I understand it's a race condition when the CachedNetworkImage is destroyed while the network request is still running.

Any ideas?


EDIT: I think I'm totally wrong here... 🙄 ☕

**Comment by dungngminh** [comment]
if you don't want Flutter throws this to any monitoring platforms. Add `errorListener` to `CachedNetworkImage` widget:

```dart
CachedNetworkImage(
      imageUrl: result.artworkUrl,
     errorListener: (error) {
       // to something with this
     },
      errorWidget: (context, error, stackTrace) {
        return Image.asset('assets/images/no_image.png');
    },
   )
),
```

Wish this will help you.

**Comment by UsamaKarim** [comment]
Try this solution.

Change this to 
```dart
 FlutterError.onError =  FirebaseCrashlytics.instance.recordFlutterFatalError;
  
```
this
```dart
// main.dart
 FlutterError.onError = (FlutterErrorDetails error) {
    if (error.exception is SocketException) return;

    if (error.exception.toString() == 'Exception: Invalid image data') return;

    FirebaseCrashlytics.instance.recordFlutterFatalError(error);
  };
```

**Comment by dungngminh** [comment]
@UsamaKarim  too risk, no one knows when the message changed and BOOM your condition will be by-passed 🙄
