### ISSUE TITLE
Invalid image data

### ISSUE THREAD

**Issue by sumanwebidigital** [Baseflow/flutter_cached_network_image#811]
======== Exception caught by image resource service ================================================
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack: 
#0      _futurize (dart:ui/painting.dart:5718:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:5574:12)
#2      instantiateImageCodec (dart:ui/painting.dart:2056:60)
<asynchronous suspension>
#3      ImageLoader.loadAsync (package:cached_network_image/src/image_provider/_image_loader.dart:59:25)
<asynchronous suspension>
#4      new MultiImageStreamCompleter.<anonymous closure> (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:25:18)
<asynchronous suspension>

**Platform:** 
- [ * ] :iphone: iOS
- [ * ] :robot: Android

**Comment by mehdico** [comment]
Same.


```
======== Exception caught by image resource service ================================================
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack: 
#0      _futurize (dart:ui/painting.dart:6408:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:6265:12)
#2      instantiateImageCodecFromBuffer (dart:ui/painting.dart:2150:60)
#3      instantiateImageCodec (dart:ui/painting.dart:2108:10)
<asynchronous suspension>
#4      ImageLoader.loadAsync (package:cached_network_image/src/image_provider/_image_loader.dart:59:25)
<asynchronous suspension>
#5      new MultiImageStreamCompleter.<anonymous closure> (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:25:18)
```

**Comment by bunny-pu** [comment]
Same issue

**Comment by MaximilianFlechtner** [comment]
+1

**Comment by zhuwei** [comment]
+1

**Comment by zhuwei** [comment]
+1

**Comment by Lemout17** [comment]
+1

**Comment by dipen-apptrait** [comment]
Any solution?

**Comment by Abdelaty** [comment]
any updates?

**Comment by limeng99** [comment]
+1
