### ISSUE TITLE
Bad state: Future already completed

### ISSUE THREAD

**Issue by kirill-21** [Baseflow/flutter_cached_network_image#880]
======== Exception caught by image resource service ================================================
The following StateError was thrown by an image listener:
Bad state: Future already completed

When the exception was thrown, this was the stack: 
#1      _decodeImage.<anonymous closure> (package:flutter_cache_manager/src/cache_managers/image_cache_manager.dart:161:15)
#2      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:651:25)
#3      MultiFrameImageStreamCompleter._emitFrame (package:flutter/src/painting/image_stream.dart:992:5)
#4      MultiFrameImageStreamCompleter._handleAppFrame (package:flutter/src/painting/image_stream.dart:916:7)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#6      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1149:11)
#7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#8      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1147:17)
#9      _invoke1 (dart:ui/hooks.dart:186:13)
#10     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:379:5)
#11     _beginFrame (dart:ui/hooks.dart:129:31)
(elided one frame from dart:async)
====================================================================================================

Hi, after the latest update i get these errors when i try to load a lot of images in a gridview, it was okay before update

**Comment by kirill-21** [comment]
![image](https://github.com/Baseflow/flutter_cached_network_image/assets/63228361/6b42cd8f-9c35-4344-90a9-bdcb044b15c6)

This happens when i set up this two variables

**Comment by UnluckyY1** [comment]
I am receiving numerous reports about the same issue on Sentry

https://oodrive.sentry.io/share/issue/b56831ea54ae48bebd9a6b69325ea1b5/
