### ISSUE TITLE
CacheManager attempt to create file named guid.* on Windows

### ISSUE THREAD

**Issue by iulian0512** [Baseflow/flutter_cached_network_image#887]
## 🐛 Bug Report

While downloading an image from a webserver the cache manager decides to create a filename ending with .* which is not permitted on windows.

### Expected behavior

Create a filename without extension or a generic extension like .cache or .file since the cache manager cannot determine it from the webserver headers.

### Reproduction steps

i have made minimal reproducible example no external dependencies needed (other than http package)
i am aware that the server should provide correct descriptive headers for the content being served but sometimes it happens not to in some scenarios.

```
import 'package:flutter_cache_manager/flutter_cache_manager.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';

Future<void> main() async {
  final client = MockClient((http.Request request) async =>
      http.Response("a png image", 200, headers: {
        "content-type": "application/*",
        "content-disposition":
            "attachment; filename=file; filename*=UTF-8''file"
      }));

  final cmgr = CacheManager(Config(DefaultCacheManager.key,
      fileService: HttpFileService(httpClient: client)));

/* crashes with
  Launching lib\main.dart on Windows in debug mode...
  √  Built build\windows\runner\Debug\cache_mgr_test.exe.
  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot open file, path = 'C:\Users\csman\AppData\Local\Temp\libCachedImageData\cf09f070-6cef-1d8a-b096-2334712b3134.*' (OS Error: The filename, directory name, or volume label syntax is incorrect.

  , errno = 123)
  #0      _checkForErrorResponse (dart:io/common.dart:55:9)
  #1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
  <asynchronous suspension>
*/

  await cmgr.downloadFile("http://myaddress.com/imageManager?pngfileid=1234");
}

/*
pubspec.yaml 

name: cache_mgr_test
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.1.5 <4.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  http: ^1.1.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
*/

```

### Configuration

**Version:** 3.3.1

**Platform:** 
Windows 10

**Comment by renefloor** [comment]
Thanks. We do have a list of pre-defined file extensions, but if it's not there it takes the part after the `/`. 
For most types that is good, but for the `*` it doesn't make sense indeed. 

That part is in [mime_converter.dart](https://github.com/Baseflow/flutter_cache_manager/blob/develop/flutter_cache_manager/lib/src/web/mime_converter.dart)
I'll fix it to not add any extension for `*`, but I also think it's not correct behaviour from a server to respond with something like `application/*`. As a request header that's fine, but in a response header I would expect a specific content-type.
