### ISSUE TITLE
Unable to use cached_network_image with widget_mask

### ISSUE THREAD

**Issue by tanmaysuryawanshi** [Baseflow/flutter_cached_network_image#905]
## 🐛 Bug Report

I am getting imageUrl from firebase and then displaying the image in particular shape by using widget_mask package. I want to cache the image but I am getting the below error when I use cached_network_image

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
`SaveLayer.child` cannot contain compositing layers.

The save layer, into which SaveLayer.child is painted, cannot encompass compositing layers.

Ensure `SaveLayer.child` contains no widgets which need compositing, such as `RepaintBoundary`.

: RenderAnimatedOpacity#b3163 NEEDS-PAINT
...  needs compositing
...  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(w=392.7, h=600.0)
...  size: Size(392.7, 600.0)
...  opacity: AnimationController#73b3d(⏭ 1.000; paused)➩Cubic(0.42, 0.00, 1.00, 1.00)➩Tween<double>(0.0 → 1.0)➩1.0
When the exception was thrown, this was the stack: 
#0      RenderSaveLayer._debugChildDoesNotNeedCompositing (package:widget_mask/src/save_layer.dart:132:7)
#1      RenderSaveLayer.needsCompositing.<anonymous closure> (package:widget_mask/src/save_layer.dart:106:9)
#2      RenderSaveLayer.needsCompositing (package:widget_mask/src/save_layer.dart:109:6)
#3      RenderObject._updateCompositingBits.<anonymous closure> (package:flutter/src/rendering/object.dart:2812:17)
#4      ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:4291:14)
#5      RenderObject._updateCompositingBits (package:flutter/src/rendering/object.dart:2810:5)
#6      RenderObject._updateCompositingBits.<anonymous closure> (package:flutter/src/rendering/object.dart:2811:13)
#7      RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#8      RenderObject._updateCompositingBits (package:flutter/src/rendering/object.dart:2810:5)
#9      RenderObject._updateCompositingBits.<anonymous closure> (package:flutter/src/rendering/object.dart:2811:13)
#10     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#11     RenderObject._updateCompositingBits (package:flutter/src/rendering/object.dart:2810:5)
#12     RenderObject._updateCompositingBits.<anonymous closure> (package:flutter/src/rendering/object.dart:2811:13)
#13     ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:4291:14)
#14     RenderObject._updateCompositingBits (package:flutter/src/rendering/object.dart:2810:5)
#15     RenderObject._updateCompositingBits.<anonymous closure> (package:flutter/src/rendering/object.dart:2811:13)
#16     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:4000:14)
#17     RenderObject._updateCompositingBits (package:flutter/src/rendering/object.dart:2810:5)
#18     PipelineOwner.flushCompositingBits (package:flutter/src/rendering/object.dart:1081:14)
#19     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:495:19)
#20     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918:13)
#21     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#22     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#23     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#24     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#25     _invoke (dart:ui/hooks.dart:170:13)
#26     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#27     _drawFrame (dart:ui/hooks.dart:140:31)

**Comment by canbalkaya** [comment]
I'm getting same problem.

**Comment by vietstone-ng** [comment]
Same
