### ISSUE TITLE
 The following assertion was thrown building Image-[<CachedNetworkImageProvider

### ISSUE THREAD

**Issue by vadimlukutin** [Baseflow/flutter_cached_network_image#926]
Have error on Android native device. In FlutterListView. Displayed image list.

[ +260 ms] ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
                    The following assertion was thrown building
                    Image-[<CachedNetworkImageProvider("http://exmpl.com/images/___res_w1280_q70/links/klsh.jpeg",
                    scale: 1.0)>](image:
                    CachedNetworkImageProvider("http://exmpl.com/images/___res_w1280_q70/links/klsh.jpeg",
                    scale: 1.0), frameBuilder: Closure: (BuildContext, Widget, int?, bool) => Widget from Function
                    '_placeholderBuilder@899215462':., loadingBuilder: null, width: 104.0, height: 104.0, fit: cover,
                    alignment: Alignment.center, this.excludeFromSemantics: false, filterQuality: low, dependencies:
                    [Directionality, MediaQuery, _EffectiveTickerMode, _LocalizationsScope-[GlobalKey#1c50b],
                    _ViewScope], state: _ImageState#4b678(stream: ImageStream#b93d9(MultiImageStreamCompleter#58415,
                    [1280×853] @ 1.0x, 1 listener), pixels: [1280×853] @ 1.0x, loadingProgress: null, frameNumber: 0,
                    wasSynchronouslyLoaded: false)):
                    'package:flutter/src/rendering/object.dart': Failed assertion: line 2103 pos 14:
                    '_debugSubtreeRelayoutRootAlreadyMarkedNeedsLayout()': is not true.
                    
                    Either the assertion indicates an error in the framework itself, or we should provide substantially
                    more information in this error message to help you determine and fix the underlying cause.
                    In either case, please report this assertion by filing a bug on GitHub:
                      https://github.com/flutter/flutter/issues/new?template=2_bug.md
                    
                    The relevant error-causing widget was:
                      Image-[<CachedNetworkImageProvider("http://exmpl.com/images/___res_w1280_q70/links/klsh.jpeg",
                      scale: 1.0)>]
                      Image:file:///home/user/.pub-cache/hosted/pub.dev/octo_image-2.0.0/lib/src/image/image_handler.dart:182:12
                    
                    When the exception was thrown, this was the stack:
                    #2      RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:2103:14)
                    #3      RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2376:11)
                    #4      RenderObject.markParentNeedsLayout (package:flutter/src/rendering/object.dart:2149:14)
                    #5      RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:2117:7)
                    #6      RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2376:11)
                    #7      RenderObject.markParentNeedsLayout (package:flutter/src/rendering/object.dart:2149:14)
                    #8      RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:2117:7)
                    #9      RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2376:11)
                    #10     RenderObject.markParentNeedsLayout (package:flutter/src/rendering/object.dart:2149:14)
                    #11     RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:2117:7)
                    #12     RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2376:11)
                    #13     RenderObject.markParentNeedsLayout (package:flutter/src/rendering/object.dart:2149:14)
                    #14     RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:2117:7)
                    #15     RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2376:11)
                    #16     RenderObject.markParentNeedsLayout (package:flutter/src/rendering/object.dart:2149:14)
                    #17     RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:2117:7)
                    #18     RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2376:11)
                    #19     RenderObject.markParentNeedsLayout (package:flutter/src/rendering/object.dart:2149:14)
                    #20     RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:2117:7)
                    #21     RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2376:11)
                    #22     RenderObject.markParentNeedsLayout (package:flutter/src/rendering/object.dart:2149:14)
                    #23     RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:2117:7)
                    #24     RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2376:11)
                    #25     RenderObject.dropChild (package:flutter/src/rendering/object.dart:1717:5)
                    #26     RenderObjectWithChildMixin.child= (package:flutter/src/rendering/object.dart:3859:7)
                    #27     SingleChildRenderObjectElement.removeRenderObjectChild (package:flutter/src/widgets/framework.dart:6464:18)
                    #28     RenderObjectElement.detachRenderObject (package:flutter/src/widgets/framework.dart:6278:37)
                    #29     Element.deactivateChild (package:flutter/src/widgets/framework.dart:4012:11)
                    #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3697:9)
                    #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
                    #32     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
                    #33     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
                    #34     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
                    #35     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
                    #36     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
                    #37     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
                    #38     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
                    #39     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
                    #40     _invoke (dart:ui/hooks.dart:142:13)
                    #41     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
                    #42     _drawFrame (dart:ui/hooks.dart:112:31)
                    (elided 2 frames from class _AssertionError)

**Comment by vadimlukutin** [comment]
Helped wrap on SizeBox
