### ISSUE TITLE
ImageLoader.loadImageAsync.<fn> FlutterError - Exception: Invalid image data. Error thrown .

### ISSUE THREAD

**Issue by karbanr** [Baseflow/flutter_cached_network_image#953]
## 🐛 Bug Report

Sometimes this issue becomes reproducible in debug mode when trying to display image through CachedNetworkImageProvider. Issue stops to reproduce right after executing command 'flutter pub get'.

### Stack trace

Exception caught by image resource service =
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data
When the exception was thrown, this was the stack:
#0  _futurize (dart:ui/painting.dart:6980:5)
#1   ImageDescriptor.encoded (dart:ui/painting.dart: 6786:12)
#2  instantiateImageCodecWithSize (dart:ui/painting.dart:2290:60)|
#3  PaintingBinding.instantiateImageCodecWithSize (package:flutter/src/painting/binding.dart:141:15)
#4  ImageLoader.loadImageAsync.<anonymous closure> (package:cached_network_image/src/image_provider/_image_loader.dart:65:22)
‹asynchronous suspension›
#5  ImageLoader._load (package:cached_network_image/src/image_provider/_image_loader.dart:124:27)
‹asynchronous suspension›
#6  new MultiImageStreamCompleter.<anonymous closure> (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:26:7)
‹asynchronous suspension›

**Version:** 3.3.1

**Platform:** 
- [ ] :iphone: iOS

**Comment by karbanr** [comment]
![Screenshot 2024-06-17 at 11 42 02 AM](https://github.com/Baseflow/flutter_cached_network_image/assets/123703351/a9352e9e-5fcd-4640-ba53-bd928334142c)

**Comment by Ali1Ammar** [comment]
I have same issus the log is keep duplicate each time we have update in state (like open / close a page) 

```
════════ Exception caught by image resource service ════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack:
#0      _futurize (dart:ui/painting.dart:7898:5)
painting.dart:7898
#1      ImageDescriptor.encoded (dart:ui/painting.dart:7692:12)
painting.dart:7692
#2      instantiateImageCodecWithSize (dart:ui/painting.dart:2546:60)
painting.dart:2546
#3      PaintingBinding.instantiateImageCodecWithSize (package:flutter/src/painting/binding.dart:147:15)
binding.dart:147
#4      ImageLoader.loadImageAsync.<anonymous closure> (package:cached_network_image/src/image_provider/_image_loader.dart:65:22)
_image_loader.dart:65
<asynchronous suspension>
#5      ImageLoader._load (package:cached_network_image/src/image_provider/_image_loader.dart:124:27)
_image_loader.dart:124
<asynchronous suspension>
#6      new MultiImageStreamCompleter.<anonymous closure> (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:26:7)
multi_image_stream_completer.dart:26
<asynchronous suspension>

Image provider: CachedNetworkImageProvider("https://prnt.sc/VLnNOiEhoxrh", scale: 1.0)
Image key: CachedNetworkImageProvider("https://prnt.sc/VLnNOiEhoxrh", scale: 1.0)
```
