### ISSUE TITLE
Database Exception (unable to open database file)

### ISSUE THREAD

**Issue by burakJs** [Baseflow/flutter_cached_network_image#964]
## 🐛 Bug Report
I saw this crash in Firebase Crashlytics. I need clarification on what this error is

```
DatabaseException(Error Domain=FMDatabase Code=14 "unable to open database file" UserInfo={NSLocalizedDescription=unable to open database file}) sql 'INSERT INTO cacheObject (url, key, relativePath, eTag, validTill, touched, length) VALUES (?, ?, ?, ?, ?, ?, ?)' args [https://images.x.com/y/z, https://images.x.com/y/z, e105bc80-299d-10e7-b9ba-155eec7740b8.octet-stream, "62721a0acb1559fee9f36afc19dd18d8", 1724274411878, 1723669612006, 728105]
```

### Configuration

**Version:** 3.3.0

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android

**Comment by zhuwei** [comment]
I also made this mistake on ios

**Comment by ZephHe** [comment]
_"DatabaseException(Error Domain=SqfliteDarwinDatabase Code=14 "unable to open database file" UserInfo={NSLocalizedDescription=unable to open database file}) sql 'UPDATE cacheObject SET url = ?, "key" = ?, relativePath = ?, eTag = ?, validTill = ?, touched = ?, length = ?, _id = ? WHERE _id = ?' args [https://eshop-img.xgd.com/partner/baseUserALIImage..., https://eshop-img.xgd.com/partner/baseUserALIImage..., badc3330-7016-11f0-bba4-4b9dd9123e0f.jpg, "5F5F0ED4FAF18274335EB6B84E84BEBE", 1754795137507, 1754707816783, 72140, 257, 257], stackTrace:#0      wrapDatabaseException (package:sqflite_platform_interface/src/platform_exception.dart:12)
<asynchronous suspension>
#1      SqfliteDatabaseMixinExt._txnRawUpdateOrDelete.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:318)
<asynchronous suspension>
#2      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33)
<asynchronous suspension>
#3      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:517)
<asynchronous suspension>"_

**I've also encountered this problem. May I ask if there are any solutions?**

**Comment by esentis** [comment]
Any luck with this issue ?
