### ISSUE TITLE
Unhandled Exception: Bad state: Stream has been disposed.

### ISSUE THREAD

**Issue by magic3584** [Baseflow/flutter_cached_network_image#993]
## 🐛 Bug Report

```shell
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Stream has been disposed.
An ImageStream is considered disposed once at least one listener has been added and subsequently all listeners have been removed and no handles are outstanding from the keepAlive method.
To resolve this error, maintain at least one listener on the stream, or create an ImageStreamCompleterHandle from the keepAlive method, or create a new stream for the image.
#0      ImageStreamCompleter._checkDisposed (package:flutter/src/painting/image_stream.dart:605)
#1      ImageStreamCompleter.reportImageChunkEvent (package:flutter/src/painting/image_stream.dart:743)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#4      _DelayedData.perform (dart:async/stream_impl.dart:515)
#5      _PendingEvents.handleNext (dart:async/stream_impl.dart:620)
#6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:40)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
```

when using in a SliverList
```dart
return CachedNetworkImage(
      imageUrl: temp,
      fit: boxFit,
      placeholder: (context, url) {
        return Image.asset('imgs/img_loading.png');
      },
    );
```
### Configuration

**Version:** 3.2.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by magic3584** [comment]
#792 
Solved by upgraded to 3.2.3
